offercompare/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^offers/', include('offers.urls', namespace="offers")),
    url(r'^admin/', include(admin.site.urls)),
]

offers/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # index pattern
    url(r'^$', views.index, name='index'),
    # details pattern
    url(r'^(?P<offer_id>[0-9]+)/$', views.detail, name='detail'),
    # url(r'^detail/', views.detail, name='detail'),
    # compare pattern
    url(r'^(?P<offer_id>[0-9]+)/compare/$', views.compare, name='compare'),
    # Results page pattern
    # url(r'^results/', views.results, name='results'),
    # new offer pattern
    url(r'^newoffer/', views.newoffer, name='newoffer'),
    # comparison page
    # url(r'^compare/', views.compare, name='compare'),
]

offers/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.forms import ModelForm

# Create your models here.

# offer classes
class Offer(models.Model):
	CURRENTJOB = 'CJ'
	NEWJOB = 'NJ'

	OFFER_CHOICES = (
		(CURRENTJOB, 'Current Job'),
		(NEWJOB, 'New Job'),
	)

	offertype = models.CharField(max_length=2, choices=OFFER_CHOICES, default=NEWJOB)
	companyname = models.CharField('company name', null=True, blank=True, max_length=100)
	positionname = models.CharField('position name', null=True, blank=True, max_length=100)
	locationzip = models.IntegerField(default=0,null=True, blank=True)
	startdate = models.DateField('start date')
	annualbase = models.IntegerField()
	salarygrowth = models.FloatField(default=.15)
	annualbonus = models.FloatField(default=.10)
	signingbonus = models.IntegerField(default=0,null=True, blank=True)
	tuitionbonus = models.IntegerField(default=0, null=True, blank=True)
	stockbonus = models.IntegerField(default=0, null=True, blank=True)
	stockgrowth = models.FloatField(default=.10, null=True, blank=True)
	discountrate = models.FloatField(default=.08)
class Other(models.Model):
	offer = models.ForeignKey(Offer)
	otherbonus = models.IntegerField(default=0, null=True, blank=True)
	bonusdate = models.DateField('other bonus date', null=True, blank=True)

class Vest(models.Model):
	offer = models.ForeignKey(Offer)
	vestingamount = models.IntegerField(default=0, null=True, blank=True)
	vestingdate = models.DateField('vest date', null=True, blank=True)

class OfferForm(ModelForm):
	class Meta:
		model = Offer
		fields = ['offertype', 'companyname', 'positionname']
		


# person classes
# class Visitor(models.Model):
# 	age = models.IntegerField(default=0,null=True, blank=True)
# 	sex = models.IntegerField(default=0,null=True, blank=True)

# class Student(Visitor):
# 	UNDERGRAD = 'UG'
# 	GRADUATE = 'GR'
# 	PHD = 'PD'
# 	EDUCATION_LEVEL = (
# 		(UNDERGRAD, 'Undergraduate Degree'),
# 		(GRADUATE, 'Masters Degree'),
# 		(PHD, 'Doctors Degree'),
# 	)
# 	edlevel = models.CharField(max_length=2, choices=EDUCATION_LEVEL, default=GRADUATE)

offers/forms.py
from django import forms
from .models import Offer

# Render Offer class as form
class Offerform(forms.ModelForm):
	class Meta:
		model = Offer
		fields = '__all__'
		

offers/views.py
from django.shortcuts import get_object_or_404, redirect, render
# from django.template import RequestContext, loader
import datetime

from django.utils import timezone
from .models import Offer
from .forms import Offerform

# Create your views here.
def index(request):
	latest_offers_list = Offer.objects.order_by('annualbase')
	context = {'latest_offers_list': latest_offers_list}
	return render(request, 'offers/templates/index.html', context)

def detail(request, offer_id):
	offer = get_object_or_404(Offer, pk=offer_id)
	return render(request, 'offers/templates/detail.html', {'offer':offer})

def newoffer(request):
	if request.method == "POST":
		form = Offerform(request.POST)
		if form.is_valid():
			# commit=False means the form doesn't save at this time.
            # commit defaults to True which means it normally saves.
			model_instance = form.save(commit=False)
			model_instance.timestamp = timezone.now()
			model_instance.save()
			return redirect('offers/templates/newoffer.html')
	else:
		form = Offerform()
	return render(request, 'offers/templates/newoffer.html', {'form':form})

def compare(request, offer_id):
	p = get_object_or_404(Offer, pk=offer_id)
	# return render(request, 'offers/templates/detail.html', {'form'}:form}
	# # try:
	# 	Offer.offertype=p.offertype.get(pk=request.POST['offertype'])
	# except(KeyError, offertype.DoesNotExist):
	# 	#redisplay the form
	# 	return render(request, 'offers/templates/details.html', {
	# 		'offertype':p, 'error_message=':"You didn't select a choice.",
	# 	})
	# else:
	# 	Offer.offertype = {{ choice }}

offers/templates/compare.html
<h1>Compare your offers!</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

offers/templates/detail.html
<h1>Compare your offers!</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{{ form }}

{# <form action="{% url 'offers:compare' offer.id %}" method="post">
{% csrf_token %}
{% for choice in offer.offertype %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value= "{{ choice.id }}" />
	<label for="choice{{ forloop.counter }}">{{ choice }}</label><br />
{% endfor %}
<input type="submit" value="Compare!" />
</form> #}

offers/templates/index.html
{% if latest_offers_list %}
	<table>
	{% for offer in latest_offers_list %}

	<tr> 
		<td><a href="{% url 'offers:detail' offer.id %}"> {{ offer.companyname }}</a></td>
		<td>{{ offer.annualbase }}</td>
	</tr>

	{% endfor %}
	</table>
{% else %}
	<p> No offers available </p>
{% endif %}

offers/templates/newoffer.html
<h1>Compare your offers!</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action='OfferForm' method='post'>
{% csrf_token %}
{{ form.as_p }}
<input type='submit' value='Submit' />
</form>